language: rust
dist: trusty
sudo: false

#cache deps
cache: cargo

rust:
#  - stable
#  - beta
  - nightly


env:
  matrix:
    - RELEASE="--release"
    - RELEASE=""
    - MISC="true"

script:
  - if [[ "$MISC" == "true" ]]; then cargo install cargo-audit; fi
  - if [[ "$MISC" == "true" ]]; then cargo audit ; exit ; fi
  - cargo build --verbose --all ${RELEASE}
  - cargo test --verbose --all ${RELEASE}
  - cargo run
  - cargo install --force --path .
  - cargo-cache
  - cargo cache
  - cargo cache --help
  - cargo cache --gc --dry-run
  - cargo cache --gc --dry-run
  - cargo cache --info
  - cargo cache --list-dirs
  - cargo cache --keep-duplicate-crates 10 --dry-run
  - cargo cache --keep-duplicate-crates 1 --dry-run
  - cargo cache --keep-duplicate-crates 0 --dry-run
  - cargo cache --keep-duplicate-crates 10
  - cargo cache --keep-duplicate-crates 1
  - cargo cache --keep-duplicate-crates 0
  - cargo cache -k 0
