language: rust
dist: trusty
sudo: false

#cache deps
cache: cargo

rust:
  - stable
  - beta
  - nightly
#matrix:
#  allow_failures:
#    - rust: nightly
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo build --verbose --all --release
  - cargo test --verbose --all --release
  - cargo run
  - cargo install --force
  - cargo-cache
  - cargo cache
  - cargo cache --help
  - cargo cache --gc --dry-run
  - cargo cache --gc --dry-run
  - cargo cache --info
  - cargo cache --list-dirs
  - cargo cache --remove-crates 0 --dry-run
  - cargo cache -c 0
