language: rust
dist: xenial
sudo: false

#cache deps
#cache: cargo

env:
  global:
    - RUST_BACKTRACE=full

matrix:
  fast_finish: false
  include:
    - name: "windows nightly debug"
      os: windows
      rust: nightly
      env: RELEASE="" DEBUG="--debug"

script:
  - cargo build --all ${RELEASE}
  - cargo test --all ${RELEASE} -j 1 -- --nocapture

