language: rust
dist: trusty
sudo: false

#cache deps
#cache: cargo

rust:
#  - stable
#  - beta
  - nightly


env:
  matrix:
    - RELEASE="" DEBUG="--debug"
    - CLIPPY="true"
    - CARGO_AUDIT="true"
    - RUSTFMT="true"
    - RELEASE="--release"

script:
  - if [[ "$CARGO_AUDIT" == "true" ]]; then cargo install cargo-audit; fi
  - if [[ "$CARGO_AUDIT" == "true" ]]; then cargo audit; exit; fi
  - if [[ "$CLIPPY" == "true" ]]; then rustup component add clippy-preview --toolchain=nightly || cargo install clippy --force || cargo install --git https://github.com/rust-lang-nursery/rust-clippy/ --force clippy ; fi
  - if [[ "$CLIPPY" == "true" ]]; then cargo clippy --all-targets --all-features -- -D warnings ; exit ; fi
  - if [[ "$RUSTFMT" == "true" ]]; then rustup component add rustfmt-preview --toolchain=nightly || cargo install rustfmt-nightly --force || cargo install --git https://github.com/rust-lang-nursery/rustfmt/ --force; fi
  - if [[ "$RUSTFMT" == "true" ]]; then cargo fmt --all -- --check ; exit ; fi
  - cargo build --all ${RELEASE}
  - cargo test --all --all-features ${RELEASE}
  - if [[ "$RELEASE" == "true" ]]; then cargo bench; fi
  - if [[ "$RELEASE" == "true" ]]; then cargo bench --features bench; fi
  - cargo run
  - cargo install --force --path . ${DEBUG}
  - cargo-cache
  - cargo cache
  - cargo cache --help
  - cargo cache --gc --dry-run
  - cargo cache --gc
  - cargo cache --info
  - cargo cache --list-dirs
  - cargo cache --keep-duplicate-crates 10 --dry-run
  - cargo cache --keep-duplicate-crates 1 --dry-run
  - cargo cache --keep-duplicate-crates 0 --dry-run
