language: rust
dist: trusty
sudo: false

#cache deps
cache: cargo

rust:
#  - stable
#  - beta
  - nightly


env:
  matrix:
    - RELEASE="--release"
    - RELEASE=""
    - CLIPPY="true"
    - CARGO_AUDIT="true"

script:
  - if [[ "$CARGO_AUDIT" == "true" ]]; then cargo install cargo-audit; fi
  - if [[ "$CARGO_AUDIT" == "true" ]]; then cargo audit; exit; fi
  - if [[ "$CLIPPY" == "true" ]]; then rustup component add clippy-preview --toolchain=nightly; fi
  - if [[ "$CLIPPY" == "true" ]]; then cargo clippy --all-targets --all-features -- -D warnings ; exit ; fi
  - cargo build --verbose --all ${RELEASE}
  - cargo test --verbose --all ${RELEASE}
  - cargo run
  - cargo install --force --path .
  - cargo-cache
  - cargo cache
  - cargo cache --help
  - cargo cache --gc --dry-run
  - cargo cache --gc --dry-run
  - cargo cache --info
  - cargo cache --list-dirs
  - cargo cache --keep-duplicate-crates 10 --dry-run
  - cargo cache --keep-duplicate-crates 1 --dry-run
  - cargo cache --keep-duplicate-crates 0 --dry-run
  - cargo cache --keep-duplicate-crates 10
  - cargo cache --keep-duplicate-crates 1
  - cargo cache --keep-duplicate-crates 0
  - cargo cache -k 0
