[package]
name = "cargo-cache"
version = "0.1.0"
authors = ["Matthias Krüger <matthias.krueger@famsik.de>"]
description = "Manage cargo cache, show sizes and delete directories."
homepage = "https://github.com/matthiaskrgr/cargo-cache"
repository = "https://github.com/matthiaskrgr/cargo-cache"
keywords = ["cargo", "cache", "delete", "manage","size"]

[dependencies]

walkdir = "2.1" # walk content of directory/CARGO_HOME recursively

[[bin]]
path = "src/main.rs"
name = "cargo-cache"

[badges]
travis-ci = { repository = "matthiaskrgr/cargo-cache", branch = "master" }

[profile.release]
lto = true
codegen-units=1
