[package]
name = "cargo-cache"
version = "0.1.0"
authors = ["Matthias Krüger <matthias.krueger@famsik.de>"]
description = "Manage cargo cache"

[dependencies]
clap = "2.28"
walkdir = "2.0"
humansize = "1.0"
cargo = "0.23"
git2 = "0.6"

[profile.release]
lto = true
