[package]
name = "cargo-cache"
version = "0.1.0"
authors = ["Matthias Krüger <matthias.krueger@famsik.de>"]
description = "Manage cargo cache, show sizes and delete directories."
homepage = "https://github.com/matthiaskrgr/cargo-cache"
repository = "https://github.com/matthiaskrgr/cargo-cache"
license = "MIT/Apache-2.0"
keywords = ["cargo", "cache", "delete", "manage", "size"]
build = "src/build.rs"
edition = "2018"

[features]
bench = [] # run benchmarks

[dependencies]
# https://github.com/kbknapp/clap-rs
clap = "2.32" # cmdline arg parsing

# https://github.com/BurntSushi/walkdir
walkdir = "2.2" # walk content of directory/CARGO_HOME recursively

# https://github.com/LeopoldArkham/humansize
humansize = "1.1" # convert digits of bytes to human readable size

# https://github.com/rust/cargo
cargo = "0.31" # get CARGO_HOME

# https://github.com/alexcrichton/git2-rs
git2 = "0.7" # check if repo is git repo

# https://github.com/rayon-rs/rayon
rayon = "1.0" # parallel for iterators

# https://github.com/rust-lang-nursery/rust-clippy
rustc_tools_util = { git = "https://github.com/rust-lang-nursery/rust-clippy", rev = "f40c4fa51d308bd32b4b3e3302bad8965d10ffbc" } # git version information

[dev-dependencies]
# https://github.com/colin-kiegel/rust-pretty-assertions
pretty_assertions = "0.5" # colored diff assertions

# https://github.com/rust-lang/regex
regex = "1.0" # use regex iun test
[build-dependencies]
# https://github.com/rust-lang-nursery/rust-clippy
rustc_tools_util = { git = "https://github.com/rust-lang-nursery/rust-clippy", rev = "f40c4fa51d308bd32b4b3e3302bad8965d10ffbc" } # git version information


[[bin]]
name = "cargo-cache"
path = "src/main.rs"
test = true
bench = true

[badges]
travis-ci = { repository = "matthiaskrgr/cargo-cache", branch = "master" }

[profile.release]
lto = true
codegen-units = 1

[profile.bench]
lto = true
codegen-units = 1
