[package]
name = "cargo-cache"
version = "0.1.0"
authors = ["Matthias Krüger <matthias.krueger@famsik.de>"]
description = "Manage cargo cache, show sizes and delete directories."
homepage = "https://github.com/matthiaskrgr/cargo-cache"
repository = "https://github.com/matthiaskrgr/cargo-cache"
keywords = ["cargo", "cache", "delete", "manage","size"]

[dependencies]
# https://github.com/kbknapp/clap-rs
clap = "2.30" # cmdline arg parsing
# https://github.com/BurntSushi/walkdir
walkdir = "2.1" # walk content of directory/CARGO_HOME recursively
# https://github.com/LeopoldArkham/humansize
humansize = "1.1" # convert digits of bytes to human readable size
# https://github.com/rust/cargo
cargo = "0.24" # get CARGO_HOME
# https://github.com/alexcrichton/git2-rs
git2 = "0.6" # check if repo is git repo
# https://github.com/rayon-rs/rayon
rayon = "1.0" # parallel for loops

[[bin]]
path = "src/main.rs"
name = "cargo-cache"

[badges]
travis-ci = { repository = "matthiaskrgr/cargo-cache", branch = "master" }

[profile.release]
lto = true
codegen-units=1
