[package]
name = "cargo-cache"
version = "0.1.2"
authors = ["Matthias Krüger <matthias.krueger@famsik.de>"]
description = "Manage cargo cache (~/.cargo/), show sizes and remove directories selectively"
homepage = "https://github.com/matthiaskrgr/cargo-cache"
repository = "https://github.com/matthiaskrgr/cargo-cache"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["cargo", "cache", "delete", "manage", "size"]
build = "src/build.rs"
edition = "2018"

[features]
bench = [] # run benchmarks

[dependencies]
# https://github.com/kbknapp/clap-rs
clap = "2.32.0" # cmdline arg parsing

# https://github.com/BurntSushi/walkdir
walkdir = "2.2.7" # walk content of directory/CARGO_HOME recursively

# https://github.com/LeopoldArkham/humansize
humansize = "1.1.0" # convert digits of bytes to human readable size

# https://github.com/rust/cargo
cargo = "0.32.0" # get CARGO_HOME

# https://github.com/alexcrichton/git2-rs
git2 = "0.8.0" # check if repo is git repo

# https://github.com/rayon-rs/rayon
rayon = "1.0.3" # parallelize iterators

# https://github.com/rust-lang/rust-clippy
rustc_tools_util = "0.1.1" # git version information

[dev-dependencies]
# https://github.com/colin-kiegel/rust-pretty-assertions
pretty_assertions = "0.5.1" # colored diff assertions

# https://github.com/rust-lang/regex
regex = "1.1.0" # use regex in tests

[build-dependencies]
# https://github.com/rust-lang/rust-clippy
rustc_tools_util = "0.1.1" # git version information

[[bin]]
name = "cargo-cache"
path = "src/main.rs"
test = true
bench = true

[badges]
travis-ci = { repository = "matthiaskrgr/cargo-cache", branch = "master" }

[profile.release]
lto = true
codegen-units = 1

[profile.bench]
lto = true
codegen-units = 1
