name: Rust_CI

on: [push, pull_request]
# also every 24 hours

jobs:
  build:
    runs-on: ["ubuntu-latest", "osx-latest", "windows-latest"]

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose


  build-release:
    runs-on: ["ubuntu-latest", "osx-latest", "windows-latest"]

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose

      