name: Rust_CI

on: [push, pull_request]
# also every 24 hours

jobs:
  build:
    runs-on: ["ubuntu-latest", "osx-latest", "windows-latest"]

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose


  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - name: install cargo-audit
        run: cargo install cargo-audit --debug

      - name: run cargo-audit
        run: cargo-audit

  rustfmt:
    env:
      EXIT: "false"
    runs-on: ubuntu-latest
    steps:
      - name: install rustfmt
        run: rustup component add rustfmt-preview --toolchain=nightly || cargo install rustfmt-nightly --force || cargo install --git https://github.com/rust-lang/rustfmt/ --force  || EXIT="true"

      - name: maybe exit build
        if: EXIT == "false"
        run: exit

      - name: run cargo fmt
        run: carog fmt --all -- --check