name: continuous integration

# trigger on pushes, PRs and every day at 05:00
on: 
  push:
  pull_request:
  schedule:
      - cron: '0 5 * * *'


jobs:


  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [one, two, three, four, five]
        include:
          - build: one
            os: ubuntu-latest
            toolchain: stable

          - build: two
            os: ubuntu-latest
            toolchain: beta

          - build: three
            os: ubuntu-latest
            toolchain: nightly

          - build: four
            os: macos-latest
            toolchain: stable

          - build: five
            os: windows-latest
            toolchain: stable
    steps:
    - uses: actions/checkout@v1
    - name: install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
        profile: minimal
    - run: cargo build
    - run: cargo test


# windows nightly debug
  windows_nightly_debug:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        profile: minimal
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

