name: Rust_CI

# trigger on pushes, PRs and every day at 05:00
on: 
  push:
  pull_request:
  schedule:
      - cron: '0 5 * * *'

strategy:
  matrix:
    os: [ubuntu-latest, windows-latest, macos-latest]
    mode: ["--release", "--debug"]


jobs:

  bla:
    runs-on:  ${{ matrix.os }}
    steps:
    - name: ${{ matrix.mode }}
    - run: echo 1
      

  build_nightly:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        profile: minimal
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose


# check for vulns in deps with cargo-audit
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        profile: minimal
    - name: install cargo-audit
      run: cargo install cargo-audit --debug
    - name: run cargo-audit
      run: cargo-audit

# code with clippy
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        profile: default
    - name: clippy
      run: cargo clippy --all-targets --all-features

# make sure code formatting is consistent
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        profile: default
    - name: rustfmt check formatting
      run: cargo fmt --all -- --check